site_name: Siddhi Execution Reorder
site_description: Siddhi Execution Reorder Extension
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-execution-reorder/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: siddhi-execution-reorder
repo_url: https://github.com/wso2-extensions/siddhi-execution-reorder
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome: index.md
- API Docs:
  - 5.0.1: api/5.0.1.md
  - 5.0.0: api/5.0.0.md
  - 4.2.2: api/4.2.2.md
  - 4.2.1: api/4.2.1.md
  - 4.2.0: api/4.2.0.md
  - 4.1.1: api/4.1.1.md
  - 4.1.0: api/4.1.0.md
  - 4.0.23: api/4.0.23.md
  - 4.0.22: api/4.0.22.md
  - 4.0.21: api/4.0.21.md
  - 4.0.20: api/4.0.20.md
  - 4.0.6: api/4.0.6.md
  - latest: api/latest.md
- License: license.md
